name: deploy

on:
  push:
    branches: [main]

jobs:
  build_and_publish:
    uses: ./.github/workflows/docker-publish.yml
    with:
        docker_file: Dockerfile
        image_name: ${{ vars.IMAGE_NAME }}
        platforms: linux/arm64,linux/amd64
    secrets:
        docker_username: ${{ secrets.REPO_USERNAME }}
        docker_password: ${{ secrets.REPO_PASSWORD }}