name: deploy

on:
  push:
    branches: [main]

jobs:
  dotnet_release_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      # Determine version
      - name: Determine version
        id: version
        run: |
          "VERSION_TAG=$(get-date -format yyyyMMddHHmmss)" >> $env:GITHUB_OUTPUT

      - uses: actions/checkout@v4

  build_and_publish:
    uses: ./.github/workflows/docker-publish.yml
    with:
        docker_file: Dockerfile
        image_name: ${{ vars.IMAGE_NAME }}
        platforms: linux/arm64,linux/amd64
        version: ${{ steps.version.outputs.VERSION_TAG }}
    secrets:
        docker_username: ${{ secrets.REPO_USERNAME }}
        docker_password: ${{ secrets.REPO_PASSWORD }}